### ISSUE TITLE
Only chef server

### ISSUE THREAD

**Issue by tboerger** [drone-plugins/drone-chef#3]
Hi,

I would suggest to limit the functionality only to chef server interaction as we already got another plugin that is scoped to the chef supermarket.

**Comment by jmccann** [comment]
I initially wrote this as a plugin for deploying Chef code.  But I do agree Chef Server and Chef Supermarket are 2 different repositories and probably could have separate plugins.

My only real concern however is this already works and the placeholder plugin repo seems a work in progress still.  I think until the other one is finished this one still has value to people as it is.

**Comment by tboerger** [comment]
@jmccann feel free to split the functionality and add the supermarket functionality to the other repo. The chef parts are not that high on my priority list, so it will take anyway some time to get the other plugin finished.

**Comment by jmccann** [comment]
I believe supermarket has been removed as part of #6.  So should be good to close this issue now.
